CREATE TABLE IF NOT EXISTS blog_posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(100) NOT NULL,
  created_at DATE DEFAULT CURRENT_DATE,
  updated_at DATE DEFAULT CURRENT_DATE
);

-- Insertting sample data
INSERT INTO blog_posts (title, content, author) VALUES
  ('My First Blog Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt magna elit, vel luctus nisi tincidunt eu. Quisque ultrices lacus non augue feugiat rhoncus. Suspendisse ultrices libero tellus, ac dictum urna lobortis et. Duis eget lorem ac enim vestibulum pretium. Quisque finibus felis orci, a venenatis metus blandit feugiat. Nulla iaculis dignissim elit ornare aliquam. Etiam elementum neque a quam semper auctor. Aenean ullamcorper nulla justo, non iaculis dolor feugiat eu. Pellentesque auctor hendrerit enim sit amet dignissim. In volutpat leo lectus, nec tincidunt elit auctor dignissim. Aenean ut enim pharetra, mollis mauris eget, aliquet augue. Nullam vitae gravida nulla.', 'Jaydon Hodge'),
  ('Learning TypeScript', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras facilisis auctor justo id egestas. In vulputate mauris at odio consequat venenatis. Maecenas sodales sapien sit amet eros venenatis commodo sit amet ut turpis. Vivamus mollis non elit eget faucibus. Donec sed malesuada velit. Etiam ac lorem magna. Curabitur ac erat eget eros viverra gravida in in massa. Vestibulum tellus felis, convallis quis dui eget, accumsan porta nisl. Nunc mi nibh, pharetra sit amet luctus sit amet, lobortis quis metus. Pellentesque pellentesque aliquet neque eu euismod. Duis accumsan massa vitae augue interdum fermentum eu non dolor. Morbi et ullamcorper nisl. Sed.', 'Jaydon Hodge'),
    ('This Week in GameDev','Sed in lobortis orci. Morbi et aliquet sem, sit amet convallis tellus. Nam ut varius arcu. Fusce congue sed diam ac ultricies. Pellentesque vel sodales velit, non pellentesque mauris. Aliquam pretium tristique metus, vitae pellentesque ex finibus quis. Sed lacinia purus vitae ex efficitur consequat. Nunc ut ullamcorper lacus. Nullam tincidunt dui et velit dictum egestas. Proin purus massa, tincidunt eget luctus sit amet, dictum vel neque. Ut eget nisl sed diam iaculis egestas.
    Nunc eu ipsum metus. Nunc at pellentesque est, sed consectetur mauris. Vestibulum vel tortor eu sem porta tempor. Maecenas ut pellentesque lectus. Nunc ullamcorper gravida odio.', 'Jaydon Hodge'),
    ('Is AI a Bubble?','Quisque elementum justo nisi. Etiam at diam non orci cursus luctus volutpat non turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas ante nulla, molestie at aliquam et, consequat ac metus. Proin finibus nunc ut metus ultrices vulputate. Suspendisse maximus leo sit amet lorem pulvinar scelerisque nec vulputate orci. Morbi est dolor, tincidunt id semper vel, convallis ut augue. Morbi bibendum sapien et venenatis feugiat. Nulla vel risus semper metus gravida egestas vel nec metus. Nullam at mauris vel lorem bibendum mattis vel sed ipsum. Vivamus vitae tortor pharetra, elementum eros tristique, pharetra dolor. Aliquam.','Jaydon Hodge'),
    ('Where do I See Myself in 5 Years','Ut facilisis, augue non pulvinar placerat, ipsum ex dignissim arcu, vel lacinia quam mauris a erat. Fusce quis turpis venenatis, consectetur lacus nec, aliquet massa. Nunc bibendum ac augue ac sagittis. Maecenas tincidunt convallis metus at malesuada. Cras volutpat ligula augue, a efficitur nisi rhoncus a. Vivamus gravida lectus ligula, ultrices consectetur nulla efficitur ac. Vivamus et consectetur eros. Aenean a laoreet dolor. Sed semper ultricies ultricies. Etiam ut ante mi. Duis pharetra nunc ut enim pretium tempus. In vel tincidunt diam, in aliquam orci. Proin ligula tellus, fermentum et sem sed, aliquam malesuada mi. Sed libero odio, malesuada et.','Jaydon Hodge'),
    ('Favorite Memories From Undergrad','Aliquam finibus turpis quis varius accumsan. Vestibulum laoreet elementum libero non commodo. Donec in ornare nulla, at viverra mauris. Praesent turpis nisl, malesuada id euismod vitae, condimentum sed purus. Vestibulum lacus justo, placerat quis hendrerit et, ultricies non velit. Morbi pharetra, diam ut lacinia iaculis, ante nulla rutrum erat, eget aliquam urna erat sed elit. Cras id consequat nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sit amet nulla magna.
    Praesent eu lobortis ligula. Proin molestie mauris metus, ut sodales massa scelerisque vitae. Vivamus suscipit nulla in tortor faucibus, sed bibendum leo luctus.','Jaydon Hodge'),
    ('How Im Trying to Stay in Shape','Curabitur venenatis felis tellus, ut semper augue iaculis sit amet. Sed non diam dolor. Sed purus ante, suscipit vel tellus eget, congue pulvinar leo. Aenean tincidunt malesuada diam, eget ornare felis aliquam nec. Nam porta lorem quis ligula elementum, quis feugiat justo vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent gravida, urna ac cursus maximus, orci magna hendrerit nisl, vitae consequat urna ipsum quis sapien. Quisque facilisis tristique odio, nec fermentum lacus mattis sit amet. Pellentesque a maximus sapien, suscipit egestas libero. Mauris est ligula, sodales id ligula a, mollis cursus tellus. Vivamus.','Jaydon Hodge'),
    ('My Top 5 Favorite Podcasts','Mauris at efficitur enim. Proin quis ipsum sit amet magna varius placerat sit amet in ligula. Sed id eros sit amet neque imperdiet consectetur ut et tortor. Aliquam eget sapien imperdiet, lobortis leo a, ultrices turpis. Phasellus euismod vulputate lacus ac viverra. Mauris lacinia rutrum pretium. Pellentesque sit amet eros nisl. Etiam imperdiet ornare nibh id sagittis. Aenean luctus quis lacus bibendum sodales. Sed hendrerit nibh eu venenatis sagittis. Curabitur ornare risus libero, vitae varius tellus placerat ac. Cras vitae auctor eros, nec luctus metus. Vestibulum ultrices massa non congue varius. Praesent nec ex at massa elementum suscipit. Pellentesque habitant.','Jaydon Hodge'),
    ('People Who Have Inspired Me and Why','Vivamus felis neque, pharetra vitae posuere et, feugiat vel tellus. Cras eget accumsan metus. Suspendisse pulvinar eleifend ex nec viverra. Nam sagittis mi nec odio dignissim molestie. Duis a consectetur tortor. Nulla dictum risus et diam ullamcorper aliquet. Nullam ultrices turpis eget lacinia euismod. Quisque felis turpis, porttitor eu consequat vel, fermentum sit amet arcu. Curabitur vitae malesuada dui. Etiam dolor est, commodo quis ex feugiat, eleifend ultrices purus. Donec metus purus, faucibus quis elementum sit amet, vestibulum vel nisi. Fusce vehicula fermentum lectus, et scelerisque nisl laoreet nec. Nunc ut dolor vel lectus viverra feugiat ut non leo. Vestibulum.','Jaydon Hodge'),
    ('Why Being a Ravens Fan is Torture','In ac risus lobortis, tempus augue a, feugiat risus. Fusce at mauris risus. Nunc fringilla, augue eget molestie condimentum, eros nisi pulvinar nunc, vitae luctus ligula felis tincidunt nisi. Aenean vel erat in nisl dignissim congue eu at tortor. Praesent a dapibus nisi, non placerat sapien. Pellentesque at felis ac lorem viverra molestie. Nullam est lectus, sollicitudin ac porttitor et, tempor vel dui. Sed hendrerit hendrerit nunc. Donec pulvinar non leo ac porttitor. Nullam lacus massa, pellentesque vestibulum elementum non, lacinia nec lectus. Pellentesque aliquam nisi nec felis venenatis placerat. Duis eget urna tempus, dignissim augue eu, iaculis arcu. Proin.','Jaydon Hodge');
